import { test, expect } from '@playwright/test';

test('wallet-first registration entry changes between builder and employer accounts', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Join Quark' })).toBeVisible();
  await expect(page.getByLabel('Username')).toBeVisible();
  await page.screenshot({ path: 'screenshots/landing.png', fullPage: true });
  await page.getByRole('button', { name: 'Hire talent' }).click();
  await expect(page.getByLabel('Company name')).toBeVisible();
  await page.getByRole('button', { name: 'Log in', exact: true }).click();
  await expect(page.getByLabel('Username')).toHaveCount(0);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByRole('button', { name: 'Find work' }).click();
  await page.getByLabel('Username').fill('builder-demo');
  await page.getByRole('button', { name: 'Explore interactive demo' }).click();
  await expect(page.locator('.task-card')).toHaveCount(6);
});

test('complete badge, application, assignment, revision, delivery and MON approval', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore interactive demo' }).click();
  await expect(page.locator('.task-card')).toHaveCount(6);
  await page.screenshot({ path: 'screenshots/desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Skills', exact: true }).click();
  await page.getByRole('button', { name: 'Take assessment' }).first().click();
  for (let i = 0; i < 5; i++) {
    await page.getByRole('radio').first().check();
    await page.getByRole('button', { name: i === 4 ? 'Finish assessment' : 'Next', exact: true }).click();
  }
  await expect(page.getByText('You made it.')).toBeVisible();
  await page.getByRole('button', { name: 'Back to skills' }).click();
  await page.getByRole('button', { name: 'Tasks', exact: true }).click();
  await page.getByRole('button', { name: 'Build a MON payment component', exact: true }).click();
  await page.getByRole('button', { name: 'Apply for this task' }).click();
  await expect(page.getByRole('button', { name: 'Application submitted' })).toBeDisabled();
  await page.getByRole('button', { name: 'Switch to employer' }).click();
  await page.getByRole('button', { name: 'Assign worker' }).click();
  await page.getByRole('button', { name: 'Switch to worker' }).click();
  await page.getByLabel('Delivery URL').fill('https://example.com/payment-v1');
  await page.getByRole('button', { name: 'Submit delivery' }).click();
  await page.getByRole('button', { name: 'Switch to employer' }).click();
  await page.getByLabel('Request a revision', { exact: true }).fill('Add wallet error handling.');
  await page.getByRole('button', { name: 'Request revision', exact: true }).click();
  await page.getByRole('button', { name: 'Switch to worker' }).click();
  await page.getByLabel('Delivery URL').fill('https://example.com/payment-v2');
  await page.getByRole('button', { name: 'Submit delivery' }).click();
  await page.getByRole('button', { name: 'Switch to employer' }).click();
  await page.getByRole('button', { name: 'Approve & pay 12 MON' }).click();
  await expect(page.getByText('12 MON demo payment completed', { exact: true })).toBeVisible();
  await page.getByLabel('Your review').fill('Clean, well-tested component delivered on time.');
  await page.getByRole('button', { name: 'Publish review' }).click();
  await expect(page.locator('.review-panel .review-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Switch to worker' }).click();
  await page.getByRole('radio', { name: '4 stars' }).click();
  await page.getByLabel('Your review').fill('Clear brief and fast, helpful feedback.');
  await page.getByRole('button', { name: 'Publish review' }).click();
  await expect(page.locator('.review-panel .review-card')).toHaveCount(2);
  await expect(page.getByRole('button', { name: 'Publish review' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByLabel('Demo role').selectOption('worker');
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await expect(page.locator('.profile-stats')).toContainText('5.0 / 5');
  await expect(page.locator('.history')).toContainText('Build a MON payment component');
  await expect(page.locator('.rating-overview')).toContainText('Clean, well-tested component delivered on time.');
  await expect(page.locator('.rating-score')).toContainText('5.0');
  await page.reload();
  await page.getByRole('button', { name: 'Explore interactive demo' }).click();
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await expect(page.locator('.profile-stats')).toContainText('5.0 / 5');
  expect(errors).toEqual([]);
});

test('create, search, refund, profile editing, ecosystem and responsive navigation', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore interactive demo' }).click();
  await expect(page.locator('.task-card')).toHaveCount(6);
  await expect(page.getByRole('button', { name: 'Post a task', exact: true })).toHaveCount(0);
  await page.getByLabel('Demo role').selectOption('employer');
  await page.getByRole('button', { name: 'Post a task', exact: true }).first().click();
  await expect(page.getByRole('heading', { name: 'Post a task' })).toBeVisible();
  await page.getByLabel('Task title', { exact: true }).fill('Build a new escrow interface');
  await page.getByLabel('Brief & deliverables').fill('Create a tested interface for native MON escrow with complete wallet handling.');
  await page.getByLabel('Reward (MON)').fill('5');
  await page.getByRole('button', { name: 'Publish demo task' }).click();
  await page.getByLabel('Search tasks').fill('new escrow');
  await expect(page.locator('.task-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Build a new escrow interface', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel & refund escrow' }).click();
  await page.getByRole('button', { name: 'Confirm refund' }).click();
  await expect(page.locator('.status-tag')).toHaveText('Refunded');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await page.getByRole('button', { name: 'Edit profile' }).click();
  await page.getByLabel('Username').fill('Quark Studio');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await expect(page.locator('.profile-header')).toContainText('Quark Studio');
  await page.getByRole('button', { name: 'Community tasks', exact: true }).click();
  await page.getByRole('button', { name: 'Projects', exact: true }).click();
  await expect(page.locator('a.project-card')).toHaveCount(3);
  await expect(page.locator('.project-card button')).toHaveCount(0);
  await expect(page.locator('a.project-card').first()).toHaveAttribute('target', '_blank');
  await page.getByRole('button', { name: 'Programs', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Explore', exact: true })).toHaveAttribute('href', 'https://monad.xyz/developers');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Tasks', exact: true }).click();
  await expect(page.locator('.task-card')).toHaveCount(6);
  await expect(page.locator('.nav-scrim')).toHaveCount(0);
  const toast = page.getByRole('button', { name: 'Dismiss notification' });
  if (await toast.isVisible()) await toast.click();
  await page.screenshot({ path: 'screenshots/mobile.png', fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Reset demo', exact: true }).click();
  await expect(page.getByLabel('Demo role')).toHaveValue('worker');
});
