'use client';

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownUp, ArrowLeft, ArrowRight, ArrowUpRight, Award, Bell, BriefcaseBusiness, Building2, Check, CheckCheck, ChevronRight, CircleCheck, Clock3, Code2, Copy, ExternalLink, FlaskConical, Globe2, LayoutGrid, LoaderCircle, LockKeyhole, LogOut, MessageSquareText, Plus, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Sparkles, Star, TriangleAlert, Unplug, UserRound, Wallet, X } from 'lucide-react';
import { useBalance } from 'wagmi';
import { formatUnits } from 'viem';
import { api, demoPrograms, demoProjects, isDemo, isShared, useMarket, type Market } from '@/lib/use-market';
import { reviewedBy, summarizeReviews } from '@/lib/reviews';
import { safeExternalUrl } from '@/lib/validators';
import type { Exam, Level, Program, Project, Review, Task } from '@/lib/types';

type View = 'board' | 'post' | 'workspace' | 'skills' | 'community' | 'earnings' | 'profile';
const allNav = [{ id: 'board', label: 'Tasks', icon: LayoutGrid }, { id: 'post', label: 'Post a task', icon: Plus }, { id: 'community', label: 'Community tasks', icon: Globe2 }, { id: 'earnings', label: 'Earnings', icon: Wallet }, { id: 'workspace', label: 'Workspace', icon: BriefcaseBusiness }, { id: 'skills', label: 'Skills', icon: Award }, { id: 'profile', label: 'Profile', icon: UserRound }] as const;
// 'Post a task' is an employer-only page; workers never see it in navigation.
const navFor = (role: 'worker' | 'employer') => allNav.filter(n => n.id !== 'post' || role === 'employer');
const short = (wallet: string) => `${wallet.slice(0, 6)}...${wallet.slice(-4)}`;
const date = (timestamp: number) => new Date(timestamp * 1000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
const statusLabel = (status: string) => ({ open: 'Open for applications', assigned: 'In progress', delivered: 'In review', approved: 'Completed', rejected: 'Revision requested', refunded: 'Refunded' }[status] || status);
const levelLabel = (level: Level) => `Solidity ${level === 'basic' ? 'Basic' : 'Expert'}`;
const categories = ['All tasks', 'Development', 'Security', 'Testing', 'Review'];
const iconFor = (category: string) => category === 'Security' ? ShieldCheck : category === 'Testing' ? FlaskConical : category === 'Review' ? CheckCheck : Code2;

function Modal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} className={`modal ${wide ? 'wide' : ''}`} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === ref.current) onClose(); }}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" title="Close" onClick={onClose}><X size={20} /></button></div>{children}</dialog>;
}
function MetaMaskButton({ market }: { market: Market }) {
  const mm = market.metaMask;
  const { data: balance } = useBalance({ address: mm.address, chainId: 10143, query: { enabled: !!mm.address && mm.onMonad } });
  if (!market.ready) return null;
  if (!mm.connected) return mm.installed
    ? <button className="metamask-button" disabled={!!market.busy} onClick={() => void mm.connect()}><Wallet size={15} />Connect MetaMask</button>
    : <a className="metamask-button" href="https://metamask.io/download/" target="_blank" rel="noopener noreferrer"><Wallet size={15} />Install MetaMask<ArrowUpRight size={13} /></a>;
  if (!mm.onMonad) return <button className="metamask-button warning" disabled={!!market.busy} onClick={() => void mm.switchNetwork()}><TriangleAlert size={15} />Switch to Monad</button>;
  return <div className="metamask-account" title={isDemo ? 'MetaMask is connected. Demo actions stay simulated.' : 'Connected with MetaMask'}><span className="network-indicator" /><span className="metamask-balance">{balance ? Number(formatUnits(balance.value, balance.decimals)).toLocaleString('en-US', { maximumFractionDigits: 3 }) : '0'} MON</span><strong>{short(mm.address!)}</strong>{isDemo && <button className="icon-button" aria-label="Disconnect MetaMask" title="Disconnect MetaMask" onClick={mm.disconnect}><Unplug size={14} /></button>}</div>;
}
function NotificationBell({ market, onOpen }: { market: Market; onOpen: (taskId: string) => void }) {
  const [open, setOpen] = useState(false);
  const unread = market.notifications.filter(n => !n.read).length;
  function toggle() { setOpen(!open); if (!open) void market.markNotificationsRead(); }
  return <div className="notify">
    <button className="icon-button notify-button" aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`} title="Notifications" onClick={toggle}><Bell size={17} />{unread > 0 && <span className="notify-count">{unread}</span>}</button>
    {open && <div className="notify-panel" role="dialog" aria-label="Notifications"><div className="notify-head"><strong>Notifications</strong><button className="icon-button" aria-label="Close notifications" onClick={() => setOpen(false)}><X size={14} /></button></div>
      {market.notifications.length ? market.notifications.map(n => {
        const task = market.tasks.find(t => t.id === n.taskId);
        const decide = n.kind === 'delivered' && task?.status === 'delivered' && task.employer === market.wallet;
        return <article key={n.id} className={`notify-item ${n.read ? '' : 'unread'}`}><p>{n.message}</p><small>{new Date(n.createdAt * 1000).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</small>
          <div className="notify-actions">{decide && task ? <><button className="button primary small" disabled={!!market.busy} onClick={() => void market.action(task, 'approve', { rating: 5 })}><Check size={14} />Approve & pay {task.amount} MON</button><button className="button secondary small" onClick={() => { setOpen(false); onOpen(task.id); }}>Reject</button></> : task && <button className="text-button" onClick={() => { setOpen(false); onOpen(task.id); }}>Open task<ArrowRight size={13} /></button>}</div></article>;
      }) : <p className="muted notify-empty">No notifications yet.</p>}</div>}
  </div>;
}
function Stars({ value, size = 14 }: { value: number; size?: number }) {
  return <span className="stars" role="img" aria-label={`${value.toFixed(1)} out of 5 stars`}>{[1, 2, 3, 4, 5].map(n => <Star key={n} size={size} className={n <= Math.round(value) ? 'filled' : ''} />)}</span>;
}
function StarInput({ value, onChange, label, disabled = false }: { value: number; onChange: (value: number) => void; label: string; disabled?: boolean }) {
  const words = ['', 'Poor', 'Fair', 'Good', 'Very good', 'Excellent'];
  return <fieldset className="star-input" disabled={disabled}><legend>{label}</legend><div role="radiogroup" aria-label={label}>{[1, 2, 3, 4, 5].map(n => <button type="button" key={n} role="radio" aria-checked={value === n} aria-label={`${n} star${n > 1 ? 's' : ''}`} className={n <= value ? 'filled' : ''} onClick={() => onChange(n)}><Star size={22} /></button>)}<span>{value ? `${value}/5 · ${words[value]}` : 'Select a rating'}</span></div></fieldset>;
}
function ReviewCard({ review }: { review: Review }) {
  return <article className="review-card"><div className="review-card-top"><Stars value={review.rating} /><small>{date(review.createdAt)}</small></div><p>{review.comment}</p><footer><span className="avatar">{review.fromName.slice(0, 1)}</span><span><strong>{review.fromName}</strong><small>{review.fromRole === 'employer' ? 'Employer' : 'Builder'} · {review.taskTitle}</small></span></footer></article>;
}
/** Overall evaluation: aggregate score, star distribution and filterable review list. */
function RatingOverview({ reviews }: { reviews: Review[] }) {
  const [filter, setFilter] = useState<'all' | 'worker' | 'employer'>('all');
  const visible = reviews.filter(r => filter === 'all' || (filter === 'worker' ? r.fromRole === 'employer' : r.fromRole === 'worker'));
  const summary = summarizeReviews(visible);
  return <section className="profile-section rating-overview" aria-label="Overall evaluation"><div className="section-title"><div><span className="eyebrow">WHAT COLLABORATORS SAY</span><h2>Overall evaluation</h2></div><div className="category-tabs">{(['all', 'worker', 'employer'] as const).map(f => <button key={f} className={filter === f ? 'selected' : ''} onClick={() => setFilter(f)}>{f === 'all' ? 'All reviews' : f === 'worker' ? 'As builder' : 'As employer'}</button>)}</div></div>
    {summary.count ? <><div className="rating-summary"><div className="rating-score"><strong>{summary.average.toFixed(1)}</strong><Stars value={summary.average} size={17} /><small>{summary.count} review{summary.count > 1 ? 's' : ''}</small></div><div className="rating-bars">{([5, 4, 3, 2, 1] as const).map(n => <div key={n}><span>{n}<Star size={11} /></span><meter min={0} max={summary.count} value={summary.distribution[n]} aria-label={`${summary.distribution[n]} reviews with ${n} stars`} /><small>{summary.distribution[n]}</small></div>)}</div></div><div className="review-list">{visible.map(r => <ReviewCard key={r.id} review={r} />)}</div></> : <p className="muted">No reviews yet. After a task is approved, the employer and builder can rate each other.</p>}
  </section>;
}
function ReviewPanel({ task, market }: { task: Task; market: Market }) {
  const owner = market.wallet === task.employer; const worker = market.wallet === task.worker;
  const [rating, setRating] = useState(owner ? task.rating || 0 : 0); const [comment, setComment] = useState('');
  const existing = market.reviews.filter(r => r.taskId === task.id);
  const canReview = market.signedIn && (owner || worker) && !reviewedBy(market.reviews, task.id, market.wallet);
  return <section className="review-panel"><h3><MessageSquareText size={17} />Collaboration reviews</h3>
    {existing.length ? <div className="review-list">{existing.map(r => <ReviewCard key={r.id} review={r} />)}</div> : !canReview && <p className="muted">No reviews for this task yet.</p>}
    {canReview && <form className="form review-form" onSubmit={e => { e.preventDefault(); void market.review(task, rating, comment).then(ok => { if (ok) setComment(''); }); }}><StarInput label={owner ? 'Rate the builder' : 'Rate the employer'} value={rating} onChange={setRating} disabled={!!market.busy} /><label>Your review<textarea rows={3} required minLength={10} maxLength={600} value={comment} onChange={e => setComment(e.target.value)} placeholder={owner ? 'How was the quality, communication and timing?' : 'How clear was the brief and how responsive was the team?'} /></label><div className="review-form-foot"><small>{comment.trim().length}/600</small><button className="button primary" disabled={!!market.busy || !rating || comment.trim().length < 10}>Publish review</button></div></form>}
  </section>;
}
function Empty({ title, text, children }: { title: string; text: string; children?: ReactNode }) { return <div className="empty"><BriefcaseBusiness size={32} /><h3>{title}</h3><p>{text}</p>{children}</div>; }

function AuthLanding({ market, onEnter }: { market: Market; onEnter: () => void }) {
  const [intent, setIntent] = useState<'login' | 'register'>('register');
  const [role, setRole] = useState<'worker' | 'employer'>('worker');
  const [name, setName] = useState('');
  const [company, setCompany] = useState('');
  async function submit(e: FormEvent) {
    e.preventDefault();
    if (isDemo) { await market.setRole(role); onEnter(); return; }
    const ok = await market.login(role, intent, intent === 'register' ? { displayName: name.trim(), ...(role === 'employer' ? { companyName: company.trim() } : {}) } : undefined);
    if (ok) onEnter();
  }
  return <div className="landing-shell">
    <header className="landing-header"><a className="brand" href="#home"><img src="/icon.svg" alt="" width="36" height="36" />quark<span>MON WORK</span></a><div className="landing-header-right"><span className="landing-network"><i />Monad Testnet</span><a href="https://monad.xyz" target="_blank" rel="noreferrer">About Monad<ArrowUpRight size={14} /></a></div></header>
    <main className="landing-main">
      <section className="landing-copy"><div className="landing-kicker"><Sparkles size={14} /> THE WORK LAYER FOR MONAD</div><h1>Build useful things.<br /><span>Get paid in MON.</span></h1><p className="landing-intro">A home for builders and teams. Find focused work, prove what you can do, and receive payment through on-chain escrow.</p>
        <div className="landing-proof"><div><strong>01</strong><span>Pick work that fits</span></div><div><strong>02</strong><span>Deliver with clarity</span></div><div><strong>03</strong><span>Get paid on Monad</span></div></div>
        <div className="landing-preview"><div className="preview-toolbar"><span><i /><i /><i /></span><span>LIVE TASK BOARD</span><span>MONAD TESTNET</span></div><div className="preview-task"><div className="preview-task-icon"><Code2 size={17} /></div><div className="preview-task-copy"><strong>Review a staking vault contract</strong><span>Security · Solidity Basic · 3 days</span></div><div className="preview-reward"><strong>18.5</strong><span>MON</span></div></div><div className="preview-task"><div className="preview-task-icon pink"><ShieldCheck size={17} /></div><div className="preview-task-copy"><strong>Test wallet connection flows</strong><span>Testing · Solidity Basic · 5 days</span></div><div className="preview-reward"><strong>7</strong><span>MON</span></div></div><div className="preview-escrow"><LockKeyhole size={15} /><span>Every task is funded before work begins</span><span className="preview-chain">ON-CHAIN ESCROW</span></div></div>
      </section>
      <section className="auth-panel" aria-label="Sign in or create an account"><div className="auth-panel-top"><span className="auth-eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>{intent === 'register' ? 'Join Quark' : 'Welcome back'}</h2><p>{intent === 'register' ? 'Create your profile with a wallet. No password to remember.' : 'Sign in securely with the wallet linked to your Quark account.'}</p></div>
        <div className="auth-tabs"><button type="button" className={intent === 'register' ? 'selected' : ''} onClick={() => setIntent('register')}>Create account</button><button type="button" className={intent === 'login' ? 'selected' : ''} onClick={() => setIntent('login')}>Log in</button></div>
        <form className="auth-form" onSubmit={submit}><span className="field-caption">I'M HERE TO</span><div className="role-choice"><button type="button" className={role === 'worker' ? 'chosen' : ''} onClick={() => setRole('worker')}><UserRound size={17} /><span><strong>Find work</strong><small>Builder / worker</small></span><i /></button><button type="button" className={role === 'employer' ? 'chosen' : ''} onClick={() => setRole('employer')}><Building2 size={17} /><span><strong>Hire talent</strong><small>Employer / team</small></span><i /></button></div>
          {intent === 'register' && <><label>Username<input autoComplete="username" minLength={2} maxLength={40} required={!isDemo} placeholder="e.g. monadbuilder" value={name} onChange={e => setName(e.target.value)} /></label>{role === 'employer' && <label>Company name<input autoComplete="organization" minLength={2} maxLength={80} required={!isDemo} placeholder="Your team or company" value={company} onChange={e => setCompany(e.target.value)} /></label>}</>}
          <button className="button primary auth-submit" disabled={!!market.busy}>{isDemo ? <><FlaskConical size={17} />Explore interactive demo</> : <><Wallet size={17} />{intent === 'register' ? 'Connect MetaMask & create account' : 'Connect MetaMask & log in'}</>}</button>
          {!isDemo && market.ready && !market.metaMask.installed && <div className="auth-error" role="note">MetaMask is required. <a href="https://metamask.io/download/" target="_blank" rel="noopener noreferrer">Install MetaMask</a>, then reload this page.</div>}
          {market.error && <div className="auth-error" role="alert">{market.error}</div>}
          <div className="auth-wallet-note"><ShieldCheck size={15} /><span>{isDemo ? 'Preview mode · no wallet or real tokens used' : 'MetaMask signature only · no custody · MON on Monad'}</span></div>
        </form>
        <div className="auth-foot"><span>By continuing, you agree to our community guidelines.</span><span>MON only <b>·</b> Monad Testnet</span></div>
      </section>
    </main>
    <footer className="landing-footer"><span>quark<span>·</span>Work that builds Monad.</span><span>Skills <b>·</b> Community <b>·</b> MON</span></footer>
  </div>;
}
function TaskCard({ task, onOpen, wallet }: { task: Task; onOpen: () => void; wallet: string }) {
  const Icon = iconFor(task.category);
  return <article className="task-card"><div className="card-top"><span className={`task-icon ${task.category.toLowerCase()}`}><Icon size={21} /></span><span className="task-company">{task.employerName}<span>{isDemo ? 'Demo project' : 'Monad builder'}</span></span><span className={`status-dot ${task.status}`} title={statusLabel(task.status)} /></div><button className="task-title" onClick={onOpen}>{task.title}</button><p className="task-summary">{task.description}</p><div className="tags"><span>{task.category}</span><span className={task.level === 'expert' ? 'expert-tag' : ''}><ShieldCheck size={12} />{levelLabel(task.level)}</span></div><div className="card-bottom"><div className="budget">{task.amount}<span>MON</span><small>Fixed reward</small></div><button className="card-action" onClick={onOpen} aria-label={`View ${task.title}`} title="View task">{task.employer === wallet ? 'Manage' : task.applicants.includes(wallet) ? 'Applied' : 'View task'}<ArrowUpRight size={16} /></button></div><div className="card-meta"><span><Clock3 size={13} />Due {date(task.deadline)}</span><span>{task.status === 'open' ? `${task.applicants.length} applicant${task.applicants.length !== 1 ? 's' : ''}` : statusLabel(task.status)}</span></div></article>;
}

export default function QuarkApp() {
  const market = useMarket();
  const [entered, setEntered] = useState(false);
  const [view, setView] = useState<View>('board'); const [mobileNav, setMobileNav] = useState(false);
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All tasks'); const [level, setLevel] = useState('all'); const [sort, setSort] = useState('newest');
  const [selected, setSelected] = useState<string | null>(null); const [reset, setReset] = useState(false);
  const [workspaceFilter, setWorkspaceFilter] = useState('all');
  const nav = navFor(market.role);
  const task = market.tasks.find(t => t.id === selected);
  const now = Math.floor(Date.now() / 1000);
  const openTasks = market.tasks.filter(t => t.status === 'open' && t.deadline > now);
  const myTasks = market.tasks.filter(t => t.employer === market.wallet || t.worker === market.wallet || t.applicants.includes(market.wallet));
  const boardTasks = (view === 'workspace' ? myTasks : openTasks).filter(t =>
    (category === 'All tasks' || t.category === category || view === 'workspace') && (level === 'all' || t.level === level || view === 'workspace') &&
    (view !== 'workspace' || workspaceFilter === 'all' || (workspaceFilter === 'active' ? ['assigned', 'delivered', 'rejected'].includes(t.status) : workspaceFilter === 'completed' ? t.status === 'approved' : t.status === 'open')) &&
    `${t.title} ${t.description} ${t.employerName}`.toLowerCase().includes(query.toLowerCase())
  ).sort((a, b) => sort === 'reward' ? Number(b.amount) - Number(a.amount) : sort === 'deadline' ? a.deadline - b.deadline : b.createdAt - a.createdAt);
  function navigate(next: View) { setView(next); setQuery(''); setMobileNav(false); }
  useEffect(() => { const hash = window.location.hash.slice(1); if (allNav.some(n => n.id === hash)) setView(hash as View); }, []);
  useEffect(() => { if (view === 'post' && market.role !== 'employer') setView('board'); }, [view, market.role]);
  useEffect(() => { if (!isDemo && market.signedIn) setEntered(true); }, [market.signedIn]);
  useEffect(() => { if (!isDemo && !market.signedIn) setEntered(false); }, [market.signedIn]);
  useEffect(() => { window.history.replaceState(null, '', `#${view}`); }, [view]);
  const seenNotification = useRef('');
  useEffect(() => {
    const latest = market.notifications[0];
    if (latest && !latest.read && seenNotification.current && latest.id !== seenNotification.current) market.setNotice(latest.message);
    if (latest) seenNotification.current = latest.id; else seenNotification.current = 'none';
  }, [market.notifications, market.setNotice]);
  useEffect(() => { if (!market.notice) return; const timer = setTimeout(() => market.setNotice(''), 7000); return () => clearTimeout(timer); }, [market.notice, market.setNotice]);
  if (!entered) return <AuthLanding market={market} onEnter={() => setEntered(true)} />;
  return <div className="app-shell">
    {mobileNav && <button className="nav-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'visible' : ''}`}><a className="brand" href="#board" onClick={() => navigate('board')}><img src="/icon.svg" alt="" width="33" height="33" />quark<span>beta</span></a><div className="nav-label">YOUR NEXT CHAPTER</div><nav aria-label="Main navigation">{nav.map(n => <button key={n.id} className={`nav-item ${view === n.id ? 'active' : ''}`} onClick={() => navigate(n.id)} aria-current={view === n.id ? 'page' : undefined}><n.icon size={19} />{n.label}{n.id === 'workspace' && myTasks.length > 0 && <span className="nav-count">{myTasks.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="network-card"><span className="network-indicator" /><strong>Monad Testnet</strong><span>MON only</span></div><a className="docs-link" href="https://monad.xyz/developers" target="_blank" rel="noreferrer">Builder resources<ArrowUpRight size={15} /></a><div className="sidebar-user"><span className="avatar">{(market.profile?.name || 'Q').slice(0, 1)}</span><div><strong>{market.profile?.name || 'Welcome, builder'}</strong><small>{isDemo ? `Demo ${market.role}` : market.wallet ? short(market.wallet) : 'Wallet not connected'}</small></div>{!isDemo && market.signedIn && <button className="icon-button" aria-label="Sign out" title="Sign out" onClick={() => void market.logout()}><LogOut size={16} /></button>}</div></div></aside>
    <div className="main-shell"><header className="topbar"><a className="topbar-brand" href="#board" onClick={() => navigate('board')}><img src="/icon.svg" alt="" width="34" height="34" /><span>quark<small>MON WORK</small></span></a><nav className="top-nav" aria-label="Main navigation">{nav.map(n => <button key={n.id} className={view === n.id ? 'active' : ''} onClick={() => navigate(n.id)} aria-current={view === n.id ? 'page' : undefined}><n.icon size={16} />{n.label}</button>)}</nav><div className="top-actions">{isDemo ? <><span className="demo-pill"><FlaskConical size={13} />Demo preview</span><select aria-label="Demo role" className="role-select" value={market.role} disabled={!!market.busy} onChange={e => void market.setRole(e.target.value as 'worker' | 'employer')}><option value="worker">Worker</option><option value="employer">Employer</option></select><MetaMaskButton market={market} /><button className="icon-button logout-button" aria-label="Exit demo" title="Exit demo" onClick={() => setEntered(false)}><LogOut size={17} /></button></> : <><select aria-label="Account mode" className="role-select" value={market.role} disabled={!!market.busy} onChange={e => void market.setRole(e.target.value as 'worker' | 'employer')}><option value="worker">Worker</option><option value="employer">Employer</option></select>{isShared && market.signedIn && <NotificationBell market={market} onOpen={setSelected} />}<MetaMaskButton market={market} /><button className="icon-button logout-button" aria-label="Log out" title="Log out" disabled={!!market.busy} onClick={async () => { await market.logout(); setEntered(false); }}><LogOut size={17} /></button></>}</div></header>
    {isDemo && <div className="demo-banner"><span>Interactive demo · Sample projects, simulated MON and badges. No real transactions.</span><button onClick={() => setReset(true)}>Reset demo<RefreshCw size={12} /></button></div>}
    <main>
      {market.wrongChain && <div className="alert error"><span>MetaMask is on another network. Quark runs on Monad Testnet (chain 10143).</span><button className="button secondary small" disabled={!!market.busy} onClick={() => void market.metaMask.switchNetwork()}>Switch network</button></div>}
      {market.error && <div className="alert error" role="alert"><span>{market.error}</span><button className="icon-button" aria-label="Dismiss error" onClick={() => market.setError('')}><X size={16} /></button></div>}
      {(view === 'board' || view === 'workspace') && <><div className="page-heading"><div><div className="eyebrow">BUILD SOMETHING THAT MATTERS</div><h1>{view === 'board' ? 'Find your next contribution.' : 'Your work, all in one place.'}</h1><p>{view === 'board' ? 'Put your skills to work. Build on Monad. Get paid in MON.' : 'Track applications, deliver work, and manage your task payments.'}</p></div>{market.role === 'employer' && <button className="button primary" onClick={() => navigate('post')}><Plus size={17} />Post a task</button>}</div>
      <div className="stats-strip"><div><span className="stat-icon"><BriefcaseBusiness size={18} /></span><div><small>{view === 'board' ? 'Open opportunities' : 'Your tasks'}</small><strong>{view === 'board' ? openTasks.length.toString().padStart(2, '0') : myTasks.length.toString().padStart(2, '0')}</strong></div></div><div><span className="stat-icon mint"><Wallet size={18} /></span><div><small>{view === 'board' ? 'Available rewards' : 'Total earned'}</small><strong>{view === 'board' ? openTasks.reduce((sum, t) => sum + Number(t.amount), 0).toLocaleString('en-US', { maximumFractionDigits: 3 }) : market.profile?.earned || '0'}<span>MON</span></strong></div></div><div><span className="stat-icon yellow"><ShieldCheck size={18} /></span><div><small>{view === 'board' ? 'Payment protection' : 'Verified skills'}</small><strong>{view === 'board' ? 'On-chain' : `${market.profile?.badges.length || 0} / 2`}</strong></div></div></div>
      <div className="board-layout"><section className="board-main" aria-label="Task listings"><div className="section-title"><h2>{view === 'board' ? 'Explore opportunities' : 'Task activity'}<span>{boardTasks.length}</span></h2><button className="icon-button" title="Refresh tasks" aria-label="Refresh tasks" onClick={() => void market.refresh()}><RefreshCw size={16} /></button></div><div className="search-row"><label className="search-box"><Search size={18} /><input aria-label="Search tasks" placeholder="Search tasks, projects, or keywords..." value={query} onChange={e => setQuery(e.target.value)} />{query && <button aria-label="Clear search" onClick={() => setQuery('')}><X size={14} /></button>}</label><label className="sort-select"><ArrowDownUp size={15} /><select aria-label="Sort tasks" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest first</option><option value="reward">Highest reward</option><option value="deadline">Due soonest</option></select></label></div>
      {view === 'board' ? <div className="filters"><div className="category-tabs" aria-label="Task categories">{categories.map(c => <button key={c} onClick={() => setCategory(c)} className={category === c ? 'selected' : ''}>{c}</button>)}</div><label className="skill-filter"><SlidersHorizontal size={14} /><select aria-label="Filter skill level" value={level} onChange={e => setLevel(e.target.value)}><option value="all">All levels</option><option value="basic">Basic</option><option value="expert">Expert</option></select></label></div> : <div className="category-tabs workspace-tabs">{['all', 'open', 'active', 'completed'].map(s => <button key={s} className={workspaceFilter === s ? 'selected' : ''} onClick={() => setWorkspaceFilter(s)}>{s === 'all' ? 'All activity' : s.charAt(0).toUpperCase() + s.slice(1)}</button>)}</div>}
      {market.loading || !market.ready ? <div className="loading"><LoaderCircle className="spin" size={24} />Loading tasks...</div> : boardTasks.length ? <div className="task-grid">{boardTasks.map(t => <TaskCard key={t.id} task={t} wallet={market.wallet} onOpen={() => setSelected(t.id)} />)}</div> : <Empty title={query || category !== 'All tasks' ? 'No matching tasks' : view === 'workspace' ? 'Your next contribution starts here' : 'No open tasks yet'} text={view === 'workspace' ? 'Apply to a task or post one to begin.' : 'Try a different filter or publish the first opportunity.'}><button className="button secondary" onClick={() => { navigate('board'); setCategory('All tasks'); setLevel('all'); }}>Explore tasks<ArrowRight size={15} /></button></Empty>}
      </section><aside className="board-aside"><section className="skill-callout"><div className="callout-icon"><Award size={26} /></div><span className="eyebrow">YOUR SKILLS, VERIFIED</span><h2>A small badge.<br />More possibilities.</h2><p>Earn a Solidity badge to unlock skill-gated tasks across the marketplace.</p><div className="badge-preview"><ShieldCheck size={18} /><span>Solidity<strong>{market.profile?.badges.length ? `${market.profile.badges.length} badge${market.profile.badges.length > 1 ? 's' : ''} earned` : 'Ready to get verified'}</strong></span><ArrowUpRight size={16} /></div><button className="button primary" onClick={() => navigate('skills')}>{market.profile?.badges.length ? 'View your badges' : 'Verify your skills'}<ArrowRight size={16} /></button><small>5 questions · 5 minutes · No fee</small></section><section className="how-section"><h3>Good work. Clear rewards.</h3>{[{ icon: ShieldCheck, title: 'Verify once', text: 'A skill badge that goes with you.' }, { icon: LockKeyhole, title: 'Work with confidence', text: 'The budget is funded up front.' }, { icon: Wallet, title: 'Get paid in MON', text: 'Approval releases your reward.' }].map(item => <div key={item.title}><item.icon size={17} /><span><strong>{item.title}</strong><small>{item.text}</small></span></div>)}</section><a href="https://monad.xyz/developers" target="_blank" rel="noreferrer" className="monad-link"><span className="monad-mark">M</span><span>Made for Monad builders<small>Explore the ecosystem</small></span><ArrowUpRight size={15} /></a></aside></div></>}
      {view === 'post' && market.role === 'employer' && <CreateTask market={market} onDone={() => navigate('workspace')} onCancel={() => navigate('board')} />}
      {view === 'skills' && <Skills market={market} />}
      {view === 'profile' && <ProfileView market={market} onOpen={setSelected} onSkills={() => navigate('skills')} />}
      {view === 'community' && <Ecosystem market={market} onOpen={setSelected} />}
      {view === 'earnings' && <EarningsView market={market} onTasks={() => navigate('board')} onWorkspace={() => navigate('workspace')} />}
      <footer><span>Quark<span className="footer-dot">·</span>Work that builds Monad.</span><span>Testnet only<span className="footer-dot">·</span>Fixed-price MON escrow</span></footer>
    </main></div>
    {market.notice && <div className="toast" role="status"><CircleCheck size={19} /><span>{market.notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => market.setNotice('')}><X size={15} /></button></div>}
    {market.busy && <div className="busy-indicator" role="status"><LoaderCircle className="spin" size={16} />{market.busy}...</div>}
    {market.lastTx && <a className="tx-link" href={`https://testnet.monadscan.com/tx/${market.lastTx}`} target="_blank" rel="noreferrer">Latest transaction: {short(market.lastTx)}<ExternalLink size={13} /></a>}
    {task && <TaskDetail task={task} market={market} onClose={() => setSelected(null)} onSkills={() => { setSelected(null); navigate('skills'); }} />}
    {reset && <Modal title="Reset this demo?" onClose={() => setReset(false)}><div className="modal-body"><p>Your demo tasks, badges, and profile changes on this device will be cleared. No wallet or real tokens are affected.</p><div className="form-actions"><button className="button secondary" onClick={() => setReset(false)}>Keep my progress</button><button className="button danger" onClick={() => { market.resetDemo(); setReset(false); setSelected(null); }}>Reset demo</button></div></div></Modal>}
  </div>;
}

function CreateTask({ market, onDone, onCancel }: { market: Market; onDone: () => void; onCancel: () => void }) {
  const [form, setForm] = useState({ title: '', description: '', category: 'Development', level: 'basic' as Level, amount: '', days: '7' });
  async function submit(e: FormEvent) { e.preventDefault(); const ok = await market.createTask({ ...form, deadline: Math.floor(Date.now() / 1000) + Number(form.days) * 86400 }); if (ok) onDone(); }
  return <><div className="page-heading"><div><div className="eyebrow">FOR EMPLOYERS</div><h1>Post a task</h1><p>Describe the work, fund the escrow, and hire a verified builder.</p></div></div><section className="post-task-page"><form className="form" onSubmit={submit}><div className="inline-note"><LockKeyhole size={17} /><span>{isDemo ? 'Demo escrow. No real MON is required.' : isShared ? 'No upfront lock: on approval your MetaMask pays the worker directly.' : 'Your budget is locked in escrow when you publish.'}</span></div><label>Task title<input required minLength={8} maxLength={120} placeholder="e.g. Review a staking vault contract" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Brief & deliverables<textarea required minLength={30} maxLength={6000} rows={5} placeholder="Describe the work, acceptance criteria, and expected delivery." value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><div className="form-grid"><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.slice(1).map(c => <option key={c}>{c}</option>)}</select></label><label>Required badge<select value={form.level} onChange={e => setForm({ ...form, level: e.target.value as Level })}><option value="basic">Solidity Basic</option><option value="expert">Solidity Expert</option></select></label><label>Reward (MON)<input required type="number" min="0.000001" max="1000000" step="0.000001" placeholder="12" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /></label><label>Delivery deadline<select value={form.days} onChange={e => setForm({ ...form, days: e.target.value })}><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label></div><div className="escrow-summary"><span>Total escrow</span><strong>{form.amount || '0'} MON</strong></div><p className="fine-print">Fixed-price only. One revision is available. After a rejection, an expired deadline allows an employer refund. No dispute arbitration in this MVP.</p>{!market.signedIn && <button type="button" className="button secondary" onClick={() => void market.login()}>Connect & sign in</button>}<div className="form-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary" disabled={!!market.busy || !market.signedIn}><LockKeyhole size={16} />{isDemo ? 'Publish demo task' : isShared ? 'Publish task' : 'Fund & publish'}</button></div></form></section></>;
}

function TaskDetail({ task, market, onClose, onSkills }: { task: Task; market: Market; onClose: () => void; onSkills: () => void }) {
  const [url, setUrl] = useState(''); const [reason, setReason] = useState(''); const [rating, setRating] = useState(5); const [confirm, setConfirm] = useState(false);
  const owner = market.wallet === task.employer; const worker = market.wallet === task.worker; const badge = market.profile?.badges.includes(task.level);
  const now = Math.floor(Date.now() / 1000); const expired = now > task.deadline;
  const Icon = iconFor(task.category); const locked = !['approved', 'refunded'].includes(task.status);
  return <Modal title="Task workspace" wide onClose={onClose}><div className="detail-body"><div className="detail-header"><span className={`task-icon ${task.category.toLowerCase()}`}><Icon size={25} /></span><div><span className="muted">{task.employerName}</span><h2>{task.title}</h2></div></div><div className="tags"><span>{task.category}</span><span><ShieldCheck size={13} />{levelLabel(task.level)}</span><span className={`status-tag ${task.status}`}>{statusLabel(task.status)}</span></div><div className="detail-stats"><div><small>Fixed reward</small><strong>{task.amount} MON</strong></div><div><small>Delivery deadline</small><strong>{date(task.deadline)}</strong></div><div><small>Escrow</small><strong><LockKeyhole size={14} />{locked ? isDemo ? 'Simulated' : isShared ? 'Paid on approval' : 'Funded' : task.status === 'approved' ? 'Paid' : 'Returned'}</strong></div></div><h3>The brief</h3><p className="description">{task.description}</p><div className="workflow">{['Funded', 'Assigned', 'Delivered', 'Paid'].map((s, i) => <span className={i <= ({ open: 0, assigned: 1, delivered: 2, approved: 3, rejected: 1, refunded: -1 }[task.status]) ? 'done' : ''} key={s}><span>{i < ({ open: 0, assigned: 1, delivered: 2, approved: 3, rejected: 1, refunded: -1 }[task.status]) ? <Check size={12} /> : i + 1}</span>{s}</span>)}</div>
    {task.reason && <div className="inline-note warning"><span><strong>Revision feedback</strong><br />{task.reason}<br />{task.rejections < 2 ? 'One resubmission is available.' : 'Both delivery attempts were reviewed. Refund becomes available after the deadline.'}</span></div>}
    {task.delivery && <div className="delivery-box"><div><CheckCheck size={18} /><strong>Submitted delivery</strong></div><a href={task.delivery} target="_blank" rel="noreferrer">{task.delivery}<ExternalLink size={14} /></a>{task.reviewDeadline && task.status === 'delivered' && <small>Review by {date(task.reviewDeadline)}. After this, the worker can claim payment.</small>}</div>}
    {task.status === 'approved' && <div className="payment-success"><CircleCheck size={23} /><div><strong>{task.amount} MON {isDemo ? 'demo payment completed' : 'paid to worker'}</strong><p>Reputation updated. Rating: {task.rating}/5.</p></div></div>}
    {task.status === 'approved' && <ReviewPanel task={task} market={market} />}
    {!market.signedIn && <button className="button primary" onClick={() => void market.login()} disabled={!!market.busy}><Wallet size={16} />Sign in to participate</button>}
    {task.status === 'open' && !owner && market.signedIn && <div className="task-actions">{!badge ? <><p className="muted">A {levelLabel(task.level)} badge is required to apply.</p><button className="button primary" onClick={onSkills}><Award size={16} />Earn this skill badge</button></> : <button className="button primary" disabled={!!market.busy || expired || task.applicants.includes(market.wallet)} onClick={() => void market.action(task, 'apply')}>{task.applicants.includes(market.wallet) ? <><Check size={16} />Application submitted</> : expired ? 'Application deadline passed' : <>Apply for this task<ArrowRight size={16} /></>}</button>}</div>}
    {owner && task.status === 'open' && <section className="applicants"><h3>Applicants <span className="count">{task.applicants.length}</span></h3>{task.applicants.length ? task.applicants.map(wallet => <div key={wallet} className="applicant"><span className="avatar">W</span><div><strong>{short(wallet)}</strong><small><ShieldCheck size={12} />{levelLabel(task.level)} verified</small></div><button className="button secondary small" disabled={!!market.busy || expired} onClick={() => void market.action(task, 'assign', { worker: wallet })}>Assign worker<ArrowRight size={14} /></button></div>) : <p className="muted">No applications yet. {isDemo ? 'Switch to Worker view to earn a badge and apply.' : 'Badge-holding workers can apply from the task board.'}</p>}</section>}
    {worker && (task.status === 'assigned' || (task.status === 'rejected' && task.rejections === 1)) && <form className="form delivery-form" onSubmit={e => { e.preventDefault(); void market.action(task, 'deliver', { url }); }}><label>Delivery URL<input type="url" pattern="https://.*" required placeholder="https://github.com/you/submission" value={url} onChange={e => setUrl(e.target.value)} /></label><button className="button primary" disabled={!!market.busy || expired}>Submit delivery<ArrowRight size={16} /></button></form>}
    {owner && task.status === 'delivered' && <section className="review-section"><h3>Review this delivery</h3><StarInput label="Rate the work" value={rating} onChange={setRating} disabled={!!market.busy} /><button className="button primary" disabled={!!market.busy} onClick={() => void market.action(task, 'approve', { rating })}><Check size={16} />Approve & pay {task.amount} MON</button>{now <= (task.reviewDeadline || 0) && <form className="form revision-form" onSubmit={e => { e.preventDefault(); void market.action(task, 'reject', { reason }); }}><label>{task.rejections === 0 ? 'Request a revision' : 'Reject final submission'}<textarea rows={2} required maxLength={500} value={reason} onChange={e => setReason(e.target.value)} placeholder="Explain which acceptance criteria are not met." /></label><button className="button secondary" disabled={!!market.busy}>{task.rejections === 0 ? 'Request revision' : 'Reject submission'}</button></form>}</section>}
    {!isShared && worker && task.status === 'delivered' && now > (task.reviewDeadline || Infinity) && <button className="button primary" disabled={!!market.busy} onClick={() => void market.action(task, 'claim')}>Claim overdue payment<Wallet size={16} /></button>}
    {owner && (task.status === 'open' || (!isShared && ['assigned', 'rejected'].includes(task.status) && expired)) && <div className="cancel-task">{confirm ? <><p>Cancel this task and return {task.amount} MON to the employer?</p><button className="button danger small" disabled={!!market.busy} onClick={() => void market.action(task, 'refund')}>Confirm refund</button><button className="button secondary small" onClick={() => setConfirm(false)}>Keep task</button></> : <button className="text-button danger-text" onClick={() => setConfirm(true)}>{isShared ? 'Cancel task' : 'Cancel & refund escrow'}</button>}</div>}
    {isDemo && ['open', 'assigned', 'delivered', 'rejected'].includes(task.status) && <div className="inline-note demo-fast"><Sparkles size={16} /><span>Demo shortcut: skip the steps and show the escrow payout.</span><button className="button primary small" disabled={!!market.busy} onClick={() => void market.fastComplete(task)}>Complete & pay instantly<ArrowRight size={14} /></button></div>}
    {task.worker && <p className="fine-print">Assigned worker: {short(task.worker)}</p>}{task.txHash && <a className="text-link" href={`https://testnet.monadscan.com/tx/${task.txHash}`} target="_blank" rel="noreferrer">View latest transaction<ExternalLink size={13} /></a>}
    {isDemo && <div className="inline-note demo-detail"><FlaskConical size={16} /><span>Demo role: <strong>{market.role}</strong>. </span><button className="text-button" disabled={!!market.busy} onClick={() => market.setRole(market.role === 'worker' ? 'employer' : 'worker')}>Switch to {market.role === 'worker' ? 'employer' : 'worker'}<ArrowRight size={13} /></button></div>}
    </div></Modal>;
}

function Skills({ market }: { market: Market }) {
  const [exam, setExam] = useState<Exam | null>(null); const [level, setLevel] = useState<Level>('basic'); const [answers, setAnswers] = useState<number[]>([]); const [index, setIndex] = useState(0); const [clock, setClock] = useState(Date.now()); const [result, setResult] = useState<{ passed: boolean; score: number } | null>(null);
  useEffect(() => { if (!exam) return; const timer = setInterval(() => setClock(Date.now()), 1000); return () => clearInterval(timer); }, [exam]);
  async function start(level: Level) { const attempt = await market.startExam(level); if (attempt) { setExam(attempt); setLevel(level); setAnswers(Array(5).fill(-1)); setIndex(0); setResult(null); setClock(Date.now()); } }
  const remaining = exam ? Math.max(0, Math.ceil((exam.expiresAt - clock) / 1000)) : 0;
  return <><div className="page-heading"><div><div className="eyebrow">PROOF OF WHAT YOU CAN DO</div><h1>Skills that open doors.</h1><p>One assessment. A reusable, non-transferable badge on Monad.</p></div></div><div className="skill-grid">{(['basic', 'expert'] as Level[]).map(l => { const earned = market.profile?.badges.includes(l); return <article className={`skill-card ${earned ? 'earned' : ''}`} key={l}><div className="skill-card-top"><div className="large-badge"><ShieldCheck size={36} /></div><span className="tags"><span>{l === 'basic' ? 'FOUNDATIONS' : 'ADVANCED'}</span></span></div><h2>{levelLabel(l)}</h2><p>{l === 'basic' ? 'Contract fundamentals, state, transactions, and the building blocks of secure Solidity.' : 'Access control, signature security, reentrancy, and contract edge cases.'}</p><div className="skill-facts"><span><Clock3 size={15} />5 minutes</span><span><CheckCheck size={15} />5 questions</span><span><Star size={15} />80% to pass</span></div><button className={`button ${earned ? 'secondary' : 'primary'}`} disabled={!!market.busy || earned || !market.signedIn} onClick={() => void start(l)}>{earned ? <><CircleCheck size={16} />Badge earned</> : <>Take assessment<ArrowRight size={16} /></>}</button></article>; })}</div>{!market.signedIn && <button className="button primary" onClick={() => void market.login()}>Sign in to take an assessment</button>}<section className="assessment-note"><ShieldCheck size={22} /><div><h3>Your badge belongs to you.</h3><p>{isDemo ? 'Demo assessments teach the Quark workflow. Demo badges exist only on this device and are not on-chain credentials.' : 'Passing results are signed by the assessment oracle. Mint your badge with your wallet; the only cost is testnet network gas. Failed attempts have a 10-minute cooldown.'}</p></div></section>
    {exam && <Modal title={`${levelLabel(level)} assessment`} onClose={() => { setExam(null); setResult(null); }}>{result ? <div className="exam-result"><div className={`result-icon ${result.passed ? '' : 'failed'}`}><Award size={36} /></div><h2>{result.passed ? 'You made it.' : 'Keep building.'}</h2><p>You scored {result.score}%. {result.passed ? isDemo ? 'Your demo badge is ready.' : 'Your badge transaction is confirmed.' : 'You need 80% to pass.'}</p><button className="button primary" onClick={() => setExam(null)}>Back to skills<ArrowRight size={16} /></button></div> : <div className="modal-body exam"><div className="exam-progress"><span>Question {index + 1} of {exam.questions.length}</span><span className={remaining < 60 ? 'danger-text' : ''}><Clock3 size={14} />{Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, '0')}</span></div><progress max={5} value={index + 1} /><h3>{exam.questions[index].question}</h3><fieldset disabled={remaining === 0 || !!market.busy}><legend className="sr-only">Choose one answer</legend>{exam.questions[index].options.map((option, i) => <label className={`answer ${answers[index] === i ? 'chosen' : ''}`} key={i}><input type="radio" name={`question-${index}`} checked={answers[index] === i} onChange={() => setAnswers(prev => prev.map((a, n) => n === index ? i : a))} /><span>{option}</span></label>)}</fieldset>{remaining === 0 && <p className="danger-text" role="alert">Time expired. Close the assessment and try again after the cooldown.</p>}<div className="form-actions"><button className="button secondary" disabled={index === 0} onClick={() => setIndex(index - 1)}><ArrowLeft size={15} />Back</button>{index < 4 ? <button className="button primary" disabled={answers[index] === -1 || remaining === 0} onClick={() => setIndex(index + 1)}>Next<ArrowRight size={15} /></button> : <button className="button primary" disabled={answers.some(a => a === -1) || remaining === 0 || !!market.busy} onClick={async () => { const result = await market.finishExam(level, exam, answers); if (result) setResult(result); }}>{isDemo ? 'Finish assessment' : 'Submit & mint badge'}</button>}</div></div>}</Modal>}
  </>;
}

function EarningsView({ market, onTasks, onWorkspace }: { market: Market; onTasks: () => void; onWorkspace: () => void }) {
  const worker = market.role === 'worker';
  const paidTasks = market.tasks.filter(t => t.status === 'approved' && (worker ? t.worker === market.wallet : t.employer === market.wallet));
  const activeTasks = market.tasks.filter(t => worker ? t.worker === market.wallet && ['assigned', 'delivered', 'rejected'].includes(t.status) : t.employer === market.wallet && ['open', 'assigned', 'delivered', 'rejected'].includes(t.status));
  const waiting = market.tasks.filter(t => worker ? t.worker === market.wallet && t.status === 'delivered' : t.employer === market.wallet && t.status === 'delivered');
  const total = worker ? market.profile?.earned || '0' : market.profile?.spent || '0';
  return <><div className="page-heading"><div><div className="eyebrow">{worker ? 'YOUR BUILDER PAYOUTS' : 'YOUR TEAM SPEND'}</div><h1>{worker ? 'Earnings' : 'Payments'}</h1><p>{worker ? 'Track completed work and MON paid to your wallet.' : 'Follow your funded tasks and payments released to builders.'}</p></div></div>
    <div className="earnings-summary"><article><span>Total {worker ? 'earned' : 'paid'}</span><strong>{total}<small>MON</small></strong><p>Lifetime, from confirmed escrow events</p></article><article><span>Completed tasks</span><strong>{paidTasks.length}</strong><p>{worker ? 'Payments released to your wallet' : 'Tasks approved and paid'}</p></article><article><span>In progress</span><strong>{activeTasks.length}</strong><p>Work currently active in escrow</p></article><article><span>Awaiting review</span><strong>{waiting.length}</strong><p>Delivery submitted for approval</p></article></div>
    <section className="earnings-history"><div className="section-title"><div><span className="eyebrow">SETTLEMENT HISTORY</span><h2>Recent activity</h2></div><span className="chain-chip"><i />Monad · MON</span></div>{paidTasks.length ? paidTasks.sort((a,b) => b.createdAt-a.createdAt).map(task => <article className="earning-row" key={task.id}><span className="earning-check"><Check size={17} /></span><span className="earning-task"><strong>{task.title}</strong><small>{worker ? `Paid by ${task.employerName}` : `Paid to ${task.worker ? short(task.worker) : 'builder'}`} · {date(task.createdAt)}</small></span><span className="earning-status">Settled</span><strong className={worker ? 'credit' : 'debit'}>{worker ? '+' : '-'}{task.amount} MON</strong>{task.txHash && <a href={`https://testnet.monadscan.com/tx/${task.txHash}`} target="_blank" rel="noreferrer" aria-label="View settlement on Monadscan"><ExternalLink size={15} /></a>}</article>) : <Empty title="Your first payment is ahead" text={worker ? 'Complete a task and its MON payout will appear here.' : 'Approve delivered work to see released MON payments here.'}><button className="button secondary" onClick={worker ? onTasks : onWorkspace}>{worker ? 'Explore tasks' : 'Manage tasks'}<ArrowRight size={15} /></button></Empty>}</section>
    <p className="fine-print earnings-note"><LockKeyhole size={13} />Payments are released by the Monad escrow contract after approval. The indexer may take a short time to reflect a confirmed transaction.</p>
  </>;
}

function ProfileView({ market, onOpen, onSkills }: { market: Market; onOpen: (id: string) => void; onSkills: () => void }) {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState('');
  const [company, setCompany] = useState('');
  const p = market.profile;
  const completed = market.tasks.filter(t => t.status === 'approved' && (t.worker === market.wallet || t.employer === market.wallet));
  if (!market.wallet) return <Empty title="Your work tells your story" text="Connect your wallet to see badges, earnings, and your on-chain reputation."><button className="button primary" onClick={() => void market.login()}>Connect wallet</button></Empty>;
  return <><div className="page-heading"><div><div className="eyebrow">YOUR ON-CHAIN TRACK RECORD</div><h1>Profile</h1><p>Your identity, verified skills, and work history.</p></div><button className="button secondary" onClick={() => { setName(p?.name || ''); setCompany(p?.companyName || ''); setEditing(true); }}>Edit profile</button></div>
    <section className="profile-header"><span className="profile-avatar">{(p?.name || 'Q').charAt(0)}</span><div><h2>{p?.name || 'Monad builder'}</h2><p>{p?.companyName || (market.role === 'employer' ? 'Add your company name' : 'Independent builder')}</p><button className="wallet-copy" title="Copy wallet address" onClick={() => navigator.clipboard.writeText(market.wallet).then(() => market.setNotice('Wallet address copied.')).catch(() => market.setError('Clipboard is unavailable.'))}>{short(market.wallet)}<Copy size={13} /></button></div><span className="role-badge">{market.role === 'worker' ? 'BUILDER' : 'EMPLOYER'}</span></section>
    <div className="profile-stats">{[{ label: 'Completed tasks', value: p?.completed || 0, icon: CheckCheck }, { label: 'Average rating', value: p?.rating ? p.rating.toFixed(1) + ' / 5' : 'Not rated', icon: Star }, { label: 'MON earned', value: p?.earned || '0', icon: Wallet }, { label: 'MON paid out', value: p?.spent || '0', icon: ArrowUpRight }].map(s => <div key={s.label}><s.icon size={20} /><strong>{s.value}</strong><span>{s.label}</span></div>)}</div>
    <RatingOverview reviews={market.reviews.filter(r => r.to === market.wallet)} />
    <section className="profile-section"><div className="section-title"><h2>Verified skills</h2><button className="text-button" onClick={onSkills}>Explore assessments<ArrowRight size={14} /></button></div>{p?.badges.length ? <div className="earned-badges">{p.badges.map(l => <div key={l}><Award size={26} /><span><strong>{levelLabel(l)}</strong><small>{isDemo ? 'Demo badge' : 'Soulbound credential'}</small></span><CircleCheck size={18} /></div>)}</div> : <p className="muted">No badges yet. Your first assessment takes about five minutes.</p>}</section>
    <section className="profile-section"><h2>Completed contributions</h2>{completed.length ? <div className="history">{completed.map(t => <button key={t.id} onClick={() => onOpen(t.id)}><span><strong>{t.title}</strong><small>{t.employerName} · {t.worker === market.wallet ? 'Contributor' : 'Employer'}</small></span><strong>{t.amount} MON</strong><ChevronRight size={16} /></button>)}</div> : <Empty title="A fresh start" text="Completed tasks will appear here after approval." />}</section>
    {!isDemo && !isShared && <button className="text-button" onClick={() => void market.recoverMetadata()}><RefreshCw size={14} />Recover pending task details</button>}
    {editing && <Modal title="Edit profile" onClose={() => setEditing(false)}><form className="modal-body form" onSubmit={async e => { e.preventDefault(); if (await market.saveProfile(name, company)) setEditing(false); }}><label>Username<input value={name} onChange={e => setName(e.target.value)} required minLength={2} maxLength={40} /></label><label>Company name <span className="muted">(optional)</span><input value={company} onChange={e => setCompany(e.target.value)} maxLength={80} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setEditing(false)}>Cancel</button><button className="button primary" disabled={!!market.busy}>Save profile</button></div></form></Modal>}
  </>;
}

function Ecosystem({ market, onOpen }: { market: Market; onOpen: (id: string) => void }) {
  const [tab, setTab] = useState<'tasks' | 'projects' | 'programs'>('tasks');
  const [projects, setProjects] = useState<Project[]>(isDemo ? demoProjects : []);
  const [programs, setPrograms] = useState<Program[]>(isDemo ? demoPrograms : []);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(!isDemo);
  const communityTasks = market.tasks.filter(t => t.status === 'open' && t.deadline > Date.now() / 1000);
  async function load() {
    setLoading(true); setError('');
    try {
      const p = await api<{ projects: Project[] }>('/ecosystem/projects'); setProjects(p.projects.filter(project => safeExternalUrl(project.url)));
      const result = await api<{ programs: Program[] }>('/ecosystem/programs'); setPrograms(result.programs);
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load community resources.'); }
    finally { setLoading(false); }
  }
  useEffect(() => { if (!isDemo) void load(); }, []);
  return <><div className="page-heading"><div><div className="eyebrow">BUILD IN PUBLIC, BUILD TOGETHER</div><h1>Community tasks</h1><p>Open work, teams, and builder programs from across the Monad ecosystem.</p></div><span className="chain-chip"><i />Monad community</span></div>
    <div className="category-tabs ecosystem-tabs"><button className={tab === 'tasks' ? 'selected' : ''} onClick={() => setTab('tasks')}>Open tasks <span>{communityTasks.length}</span></button><button className={tab === 'projects' ? 'selected' : ''} onClick={() => setTab('projects')}>Projects</button><button className={tab === 'programs' ? 'selected' : ''} onClick={() => setTab('programs')}>Programs</button></div>
    {error && <div className="alert error">{error}<button className="button secondary small" onClick={() => void load()}>Retry</button></div>}
    {tab === 'tasks' ? communityTasks.length ? <div className="task-grid">{communityTasks.map(t => <TaskCard key={t.id} task={t} wallet={market.wallet} onOpen={() => onOpen(t.id)} />)}</div> : <Empty title="No open community tasks" text="New Monad ecosystem work will appear here as teams post and fund their tasks." /> : loading ? <div className="loading"><LoaderCircle className="spin" />Loading community...</div> : tab === 'projects' ? <div className="ecosystem-grid">{projects.map(p => {
      // Community projects only ever leave the app: the whole card is one external link, with no in-app action.
      const href = safeExternalUrl(p.url); if (!href) return null;
      return <a className="project-card project-link" key={p.id} href={href} target="_blank" rel="noopener noreferrer" aria-label={`${p.name}: open ${new URL(href).hostname} in a new tab`}><div className="project-mark">{p.name.slice(0, 1)}</div><div className="project-title"><h2>{p.name}</h2><span>{p.category}{p.demo ? ' · Sample project' : ''}</span></div><p>{p.description}</p><div className="project-actions"><span className="muted">{new URL(href).hostname}</span><span className="project-external">Visit site<ExternalLink size={15} /></span></div></a>;
    })}</div> : <div className="program-list">{programs.map(p => <article key={p.id}><span className="task-icon development"><Globe2 size={24} /></span><div><span className="eyebrow">{p.program}</span><h2>{p.title}</h2><p>{p.description}</p></div>{safeExternalUrl(p.url) && <a href={safeExternalUrl(p.url)} target="_blank" rel="noopener noreferrer" className="button secondary">Explore<ArrowUpRight size={16} /></a>}</article>)}</div>}
    <p className="fine-print ecosystem-note">Curated resources. Project listings do not imply a partnership or endorsement.</p></>;
}
